name: ntp_dart
description: Lightweight Dart package to fetch accurate UTC time from NTP servers with no external dependencies.
version: 1.2.1
homepage: https://github.com/enzo-desimone/ntp_dart

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  very_good_analysis: ^10.0.0
